from enum import StrEnum


class AllowedMethods(StrEnum):
    EDIT_TEXT = "EDIT_TEXT"
    EDIT_MEDIA = "EDIT_MEDIA"
    EDIT_MARKUP = "EDIT_MARKUP"

    REPLACE_LINKS = "REPLACE_LINKS"

    SPOILER_SWITCH = "SPOILER_SWITCH"

    DISABLE_WEB_PAGE_PREVIEW_SWITCH = "DISABLE_WEB_PAGE_PREVIEW_SWITCH"
    DISABLE_NOTIFICATIONS_SWITCH = "DISABLE_NOTIFICATIONS_SWITCH"
